default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: postgres
  username: postgres
  password: pwd
  host: localhost
  port: 5432

test:
  <<: *default
  database: gitcollections_test

production:
  <<: *default
  database: gitcollections_production
  username: gitcollections
  password: <%= ENV['GITCOLLECTIONS_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>



#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
